source 'https://rubygems.org'

gem 'rack-parser', '~>0.2.0'
gem 'sass', '~>3.2.8'
gem 'slim', '~>1.3.8'
gem 'sinatra', '~>1.4.0'
gem 'sinatra-reloader', '~>1.0'
gem 'sinatra-partial', '~>0.4.0'
gem 'thin', '~>1.5.1'
gem 'mongoid', '~>2.6.0'
gem 'mail', '~>2.5.4'
#gem 'sinatra-param', '~>0.1.3'
